- hosts: 124.71.166.144
  tasks:
    - name: nginx repo
      yum_repository: 
        name: nginx
        description: nginx repo
        baseurl: http://nginx.org/packages/centos/7/x86_64/
        enabled: yes
        gpgcheck: yes
        gpgkey: https://nginx.org/keys/nginx_signing.key
    - name: yum nginx
      yum:
        name: nginx
        state: installed
#    - name: index.html
#      copy:
#        content: 1122334455
#        dest: /usr/share/nginx/html/index.html
#    - name: copy nginx.d conf
#      copy:
#        src: ./www.conf
#        dest: /etc/nginx/conf.d/default.conf
#        backup: yes
    - name: start nginx
      systemd:
        name: nginx
        state: started
        enabled: yes
